<a href="https://colab.research.google.com/github/dukc11coco-hash/wassup13/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
https://apis.data.go.kr/B551011/KorPetTourService2
service_key = "c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97"

url = "https://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2"

params = {
    "serviceKey": service_key,
    "numOfRows": 5,
    "pageNo": 1,
    "MobileOS": "ETC",
    "MobileApp": "AppTest",
    "areaCode": 1,   # 서울
    "_type": "json"
}

response = requests.get(url, params=params)

print("Status Code:", response.status_code)
print(response.text)

Status Code: 200
{"response": {"header":{"resultCode":"0000","resultMsg":"OK"},"body": {"items": {"item":[{"addr1":"서울특별시 구로구 구로중앙로42길 27","addr2":"구로구 반려견 놀이터","areacode":"1","cat1":"A02","cat2":"A0202","cat3":"A02020700","contentid":"3112063","contenttypeid":"12","createdtime":"20240328195446","firstimage":"","firstimage2":"","cpyrhtDivCd":"","mapx":"126.8757403642","mapy":"37.5082258503","mlevel":"6","modifiedtime":"20240328214257","sigungucode":"7","tel":"","title":"구로구 반려견 놀이터","zipcode":"08205","lDongRegnCd":"11","lDongSignguCd":"530","lclsSystm1":"VE","lclsSystm2":"VE03","lclsSystm3":"VE030500"},{"addr1":"서울특별시 동대문구 서울시립대로25길 10 (전농동)","addr2":"B101호","areacode":"1","cat1":"B02","cat2":"B0201","cat3":"B02011100","contentid":"3438659","contenttypeid":"32","createdtime":"20241206132405","firstimage":"","firstimage2":"","cpyrhtDivCd":"","mapx":"127.0522138438","mapy":"37.5827620188","mlevel":"6","modifiedtime":"20241218152408","sigungucode":"11","tel":"010-7656-3228","title":"그루브하우스","zipcode":"02557","lDongRegnCd":"11","lDongSignguCd":"230","lclsSystm1":"AC","lclsSystm2":"AC06","lclsSystm3":"AC060200"},{"addr1":"서울특별시 종로구 낙산길 41","addr2":"(동숭동)","areacode":"1","cat1":"A02","cat2":"A0202","cat3":"A02020700","contentid":"129501","contenttypeid":"12","createdtime":"20070403090000","firstimage":"http://tong.visitkorea.or.kr/cms/resource/28/3506728_image2_1.jpg","firstimage2":"http://tong.visitkorea.or.kr/cms/resource/28/3506728_image3_1.jpg","cpyrhtDivCd":"Type1","mapx":"127.0065125148","mapy":"37.5805725621","mlevel":"6","modifiedtime":"20251216162846","sigungucode":"23","tel":"","title":"낙산공원","zipcode":"03085","lDongRegnCd":"11","lDongSignguCd":"110","lclsSystm1":"VE","lclsSystm2":"VE03","lclsSystm3":"VE030400"},{"addr1":"서울특별시 중구 퇴계로34길 28 (필동2가)","addr2":"","areacode":"1","cat1":"A02","cat2":"A0201","cat3":"A02010600","contentid":"126747","contenttypeid":"12","createdtime":"20040216090000","firstimage":"http://tong.visitkorea.or.kr/cms/resource/94/2932494_image2_1.bmp","firstimage2":"http://tong.visitkorea.or.kr/cms/resource/94/2932494_image3_1.bmp","cpyrhtDivCd":"Type3","mapx":"126.9932865315","mapy":"37.5597775194","mlevel":"6","modifiedtime":"20250708170501","sigungucode":"24","tel":"","title":"남산골한옥마을","zipcode":"04626","lDongRegnCd":"11","lDongSignguCd":"140","lclsSystm1":"HS","lclsSystm2":"HS01","lclsSystm3":"HS010600"},{"addr1":"서울특별시 중구 남산공원길 609 (예장동)","addr2":"","areacode":"1","cat1":"A01","cat2":"A0101","cat3":"A01010500","contentid":"2783557","contenttypeid":"12","createdtime":"20211130201410","firstimage":"http://tong.visitkorea.or.kr/cms/resource/60/3458860_image2_1.jpg","firstimage2":"http://tong.visitkorea.or.kr/cms/resource/60/3458860_image3_1.jpg","cpyrhtDivCd":"Type1","mapx":"126.9866844934","mapy":"37.5549112997","mlevel":"6","modifiedtime":"20250721093644","sigungucode":"24","tel":"","title":"남산순환나들길","zipcode":"04628","lDongRegnCd":"11","lDongSignguCd":"140","lclsSystm1":"NA","lclsSystm2":"NA05","lclsSystm3":"NA050100"}]},"numOfRows":5,"pageNo":1,"totalCount":87}}}

In [1]:
import requests

# 서비스 키
service_key = "c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97"

# 기본 URL
url = "https://apis.data.go.kr/B551011/KorPetTourService2/serviceKey"

# 파라미터
params = {
    "serviceKey": service_key,
    "numOfRows": 10,
    "pageNo": 1,
    "_type": "json"
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.text)

404
API not found

In [2]:
import requests

service_key = "c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97"

url = "http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2"

params = {
    "serviceKey": service_key,
    "MobileOS": "ETC",      # 필수인 경우가 많음
    "MobileApp": "ColabTest",
    "_type": "json",
    "numOfRows": 5,
    "pageNo": 1,
}

r = requests.get(url, params=params, timeout=20)

print("status:", r.status_code)
print("final url:", r.url)
print(r.text[:1000])

status: 200
final url: http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2?serviceKey=c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97&MobileOS=ETC&MobileApp=ColabTest&_type=json&numOfRows=5&pageNo=1
{"response": {"header":{"resultCode":"0000","resultMsg":"OK"},"body": {"items": {"item":[{"addr1":"부산광역시 부산진구 가야대로 779 (부전동)","addr2":"","areacode":"","cat1":"","cat2":"","cat3":"","contentid":"2930927","contenttypeid":"38","createdtime":"20221030154457","firstimage":"https://tong.visitkorea.or.kr/cms/resource/49/2885349_image2_1.jpg","firstimage2":"https://tong.visitkorea.or.kr/cms/resource/49/2885349_image3_1.jpg","cpyrhtDivCd":"Type3","mapx":"129.056805686045","mapy":"35.1579550616706","mlevel":"6","modifiedtime":"20260214062842","sigungucode":"","tel":"051-819-1421","title":"가까운약국","zipcode":"47257","lDongRegnCd":"26","lDongSignguCd":"230","lclsSystm1":"SH","lclsSystm2":"SH04","lclsSystm3":"SH040300"},{"addr1":"서울특별시 중구 명동8가길 33 (충무로2가)","addr2":"","areacode":"","cat1":"","cat2":"","cat3":"","contentid":"4012773","contenttypeid":"38","createdtime":"20260207014737","firstimage":"","firstimage2":"","cpyrhtDivCd":"","mapx":"126.986903352805","mapy":"37.5619124538241","mlevel":"","modi

In [3]:
import requests

service_key = "여기에_네_키"
url = "http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2"

params = {
    "serviceKey": service_key,
    "MobileOS": "ETC",
    "MobileApp": "ColabTest",
    "_type": "json",
    "numOfRows": 10,
    "pageNo": 1,
}

r = requests.get(url, params=params, timeout=20)
data = r.json()

items = data["response"]["body"]["items"]["item"]

# 핵심 필드만 출력
for it in items[:5]:
    title = it.get("title")
    addr = it.get("addr1")
    tel = it.get("tel")
    print(f"- {title} | {addr} | {tel}")

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [4]:
print(r.status_code)
print(r.text[:500])

401
Unauthorized

In [5]:
import requests

service_key = "c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97"  # (대부분 'Decoding' 키가 잘 됨)

base = "http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2"
url = f"{base}?serviceKey={service_key}"

params = {
    "MobileOS": "ETC",
    "MobileApp": "ColabTest",
    "_type": "json",
    "numOfRows": 5,
    "pageNo": 1,
}

r = requests.get(url, params=params, timeout=20)

print("status:", r.status_code)
print("content-type:", r.headers.get("Content-Type"))
print(r.text[:500])

status: 200
content-type: application/json
{"response": {"header":{"resultCode":"0000","resultMsg":"OK"},"body": {"items": {"item":[{"addr1":"부산광역시 부산진구 가야대로 779 (부전동)","addr2":"","areacode":"","cat1":"","cat2":"","cat3":"","contentid":"2930927","contenttypeid":"38","createdtime":"20221030154457","firstimage":"https://tong.visitkorea.or.kr/cms/resource/49/2885349_image2_1.jpg","firstimage2":"https://tong.visitkorea.or.kr/cms/resource/49/2885349_image3_1.jpg","cpyrhtDivCd":"Type3","mapx":"129.056805686045","mapy":"35.1579550616706","mleve

In [6]:
import requests
import pandas as pd

service_key = "여기에_네_키"

base = "http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2"
url = f"{base}?serviceKey={service_key}"

params = {
    "MobileOS": "ETC",
    "MobileApp": "ColabTest",
    "_type": "json",
    "numOfRows": 10,
    "pageNo": 1,
}

r = requests.get(url, params=params, timeout=20)
data = r.json()

items = data["response"]["body"]["items"]["item"]

df = pd.DataFrame(items)

# 필요한 컬럼만 보기 (없을 수도 있어서 있는 것만 골라줌)
cols = [c for c in ["title","addr1","tel","mapx","mapy","contentid","contenttypeid"] if c in df.columns]
df[cols].head(10)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [8]:
JSONDecodeError                           Traceback (most recent call last)
/usr/local/lib/python3.12/dist-packages/requests/models.py in json(self, **kwargs)
    975         try:
--> 976             return complexjson.loads(self.text, **kwargs)
    977         except JSONDecodeError as e:

4 frames
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
/usr/local/lib/python3.12/dist-packages/requests/models.py in json(self, **kwargs)
    978             # Catch JSON-related errors and raise as requests.JSONDecodeError
    979             # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 980             raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    981
    982     @property

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

SyntaxError: invalid syntax (ipython-input-978266523.py, line 1)

In [9]:
if "json" in r.headers.get("Content-Type", ""):
    data = r.json()
    print("JSON 성공")
else:
    print("JSON 아님, 응답 내용 확인 필요")
    print(r.text[:500])

JSON 아님, 응답 내용 확인 필요
Unauthorized

In [10]:
import requests, pandas as pd

service_key = "c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97"  # Decoding 키 추천

base = "http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2"
url = f"{base}?serviceKey={service_key}"

params = {
    "MobileOS": "ETC",
    "MobileApp": "ColabTest",
    "_type": "json",
    "numOfRows": 10,
    "pageNo": 1,
}

r = requests.get(url, params=params, timeout=20)

print("status:", r.status_code)
print("final url:", r.url)
print("content-type:", r.headers.get("Content-Type"))
print("preview:", r.text[:120])

# 200일 때만 JSON 파싱
if r.status_code == 200 and "json" in (r.headers.get("Content-Type") or ""):
    data = r.json()
    items = data["response"]["body"]["items"]["item"]
    df = pd.DataFrame(items)
    display(df[["title","addr1","tel"]].head(10))
else:
    print("❗인증/요청 문제. 위 final url/preview 확인!")

status: 200
final url: http://apis.data.go.kr/B551011/KorPetTourService2/areaBasedList2?serviceKey=c36f20fa8e010928512eff06c66f392b85ff6fc698dde757ce93564d10b03e97&MobileOS=ETC&MobileApp=ColabTest&_type=json&numOfRows=10&pageNo=1
content-type: application/json
preview: {"response": {"header":{"resultCode":"0000","resultMsg":"OK"},"body": {"items": {"item":[{"addr1":"부산광역시 부산진구 가야대로 779 (

               title                        addr1            tel
0              가까운약국    부산광역시 부산진구 가야대로 779 (부전동)   051-819-1421
1          가나안경원 명동점    서울특별시 중구 명동8가길 33 (충무로2가)
2                가든뷰     서울특별시 강서구 마곡동로 166 (마곡동)
3      가버 현대아울렛 동대문점  서울특별시 중구 장충단로13길 20 (을지로6가)
4           가야산생태탐방원       경상북도 성주군 수륜면 봉양로1길 313
5                가영당  충청북도 청주시 청원구 오창읍 미래지로 71-54   043-233-9966
6                가우도         전라남도 강진군 도암면 월곶로 473
7             가을동화펜션     강원특별자치도 평창군 봉평면 흥정계곡길 72  010-5213-3200
8  가이거 현대프리미엄아울렛 김포점    경기도 김포시 고촌읍 아라육로152번길 100
9         가인 김병로 생가터      전북특별자치도 순창군 복흥면 하리길 160

In [11]:
seoul = df[df["addr1"].fillna("").str.contains("서울")]
seoul[["title","addr1","tel"]].head(20)

           title                        addr1 tel
1      가나안경원 명동점    서울특별시 중구 명동8가길 33 (충무로2가)
2            가든뷰     서울특별시 강서구 마곡동로 166 (마곡동)
3  가버 현대아울렛 동대문점  서울특별시 중구 장충단로13길 20 (을지로6가)

In [12]:
busan = df[df["addr1"].fillna("").str.contains("부산")]
busan[["title","addr1","tel"]].head(20)

   title                      addr1           tel
0  가까운약국  부산광역시 부산진구 가야대로 779 (부전동)  051-819-1421

In [13]:
df[df["title"].fillna("").str.contains("카페")][["title","addr1","tel"]].head(20)

Empty DataFrame
Columns: [title, addr1, tel]
Index: []

In [14]:
import folium
from folium.plugins import MarkerCluster
import pandas as pd

# 좌표 컬럼을 숫자로 변환 (문자열로 오는 경우가 많음)
df2 = df.copy()
df2["mapx"] = pd.to_numeric(df2.get("mapx"), errors="coerce")
df2["mapy"] = pd.to_numeric(df2.get("mapy"), errors="coerce")

# 좌표 있는 것만
df2 = df2.dropna(subset=["mapx", "mapy"])

# 너무 많으면 느려서 200개만(원하면 숫자 바꿔도 됨)
df_plot = df2.head(50)

# 중심점(평균)으로 지도 시작
center_lat = df_plot["mapy"].mean()
center_lon = df_plot["mapx"].mean()

m = folium.Map(location=[center_lat, center_lon], zoom_start=7)

cluster = MarkerCluster().add_to(m)

for _, row in df_plot.iterrows():
    title = row.get("title", "")
    addr = row.get("addr1", "")
    tel = row.get("tel", "")

    popup = folium.Popup(f"<b>{title}</b><br>{addr}<br>{tel}", max_width=300)
    folium.Marker(
        location=[row["mapy"], row["mapx"]],
        popup=popup
    ).add_to(cluster)

m